server:
    port: 7081
spring:
    datasource:
        name: test
        url: jdbc:mysql://192.168.21.131:3306/sys
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    rabbitmq:
        host: 192.168.21.131
        port: 5672
        username: admin
        password: admin
    consul:
          host: 192.168.21.131
          port: 8500
          enabled: true
          discovery:
            enabled: true
            instance-id: service1
            service-name: service1
            hostname: 192.168.1.86
            port: 7081
            health-check-url: http://192.168.1.86:7081/health
            health-check-interval: 10s
            tags: dev
mybatis:
    type-aliases-package: com.example.service1.models
    mapper-locations: classpath:mybatis/mapper/*.xml
