server:
    port: 7081
spring:
    datasource:
        name: test
        url: jdbc:mysql://192.168.21.131:3306/sys
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
mybatis:
    type-aliases-package: com.example.service1.models
    mapper-locations: classpath:mybatis/mapper/*.xml
 rabbitmq:
    host: 192.168.21.131
    port: 5672
    username: admin
    password: admin
